import Head from 'next/head';
import SearchBar from '../components/SearchBar';
import CoinList from '../components/SearchBar/CoinList';

export default function Home({ filteredCoins }) {
	console.log(filteredCoins);
	return (
		<>
			<Head>
				<title>Crypto Tracker</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<SearchBar />
			<CoinList filteredCoins={filteredCoins} />
		</>
	);
}

export const getServerSideProps = async () => {
	const res = await fetch(
		'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_desc&per_page=10&page=1&sparkline=false'
	);

	const filteredCoins = await res.json();

	return {
		props: {
			filteredCoins,
		},
	};
};
